export enum API_Provinces {
  "AL-AJMI" = "Al-Ajmi",
  BAHARY = "Bahary",
  "AL-MANSHEYA" = "Al-Mansheya",
  "AL-RAML" = "Al-Raml",
  "AL-SHATBY" = "Al-Shatby",
  "EL-IBRAHIMEYA" = "El-Ibrahimeya",
  SPORTING = "Sporting",
  "SIDI GABER" = "Sidi Gaber",
  SOMOHA = "Somoha",
  ROSHDY = "Roshdy",
  STANLEY = "Stanley",
  GLIM = "Glim",
  "SABA PASHA" = "Saba Pasha",
  VICTORIA = "Victoria",
  "SIDI BISHR" = "Sidi Bishr",
  MIAMI = "Miami",
  ASAFRA = "Asafra",
  MANDARA = "Mandara",
  "AL AWAID" = "Al Awaid",
}
