name: CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t ezzops/khoyoutfrontend:${{ github.sha }} .
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ezzops --password-stdin
          docker push ezzops/khoyoutfrontend:${{ github.sha }}

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and update services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/traefik
            sed -i 's|image: ezzops/khoyoutfrontend:.*|image: ezzops/khoyoutfrontend:${{ github.sha }}|' docker-compose.yml
            docker-compose down
            docker-compose up -d
